### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by protestToViolence** [canturan10/satellighte-streamlit#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://share.streamlit.io/canturan10/satellighte-streamlit/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by canturan10** [comment]
Hello There 👋
Yes, the problem you mentioned occurs when a large number of visitors visit the page. I didn't think this would be a problem as there was more demand than I expected. The situation you mentioned has been resolved. I might try other solutions in case it happens again in the future. I'm closing the issue as the issue you mentioned has been resolved.
Thank you.
